import os

# the base dir of the project
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

RUBY = '/Users/grano/.rvm/rubies/ruby-2.2.1/bin'

SCRIPT_READABILITY = os.path.abspath(os.path.join(BASE_DIR, 'metrics/readability/compute_readability.rb'))

# the directory that contains the data
DATA_DIR = os.path.abspath(os.path.join(BASE_DIR, 'data'))

# directory containing the data frames to answer RQ1 (generated by the R script)
RQ1_DIR = os.path.abspath(os.path.join(DATA_DIR, 'rq1'))

# the directory that contains the plots
PLOT_DIR = os.path.abspath(os.path.join(BASE_DIR, 'plots'))

# the installation directory of Defect4j in the system
DEFECT4J = '/Users/grano/Documents/PhD/defects4j/framework/bin'

METRICS_DIR = os.path.abspath(os.path.join(BASE_DIR, 'metrics'))

# test smell jar
TEST_SMELL_JAR = os.path.abspath(os.path.join(BASE_DIR, 'metrics/test-smells/test-smells.jar'))

# code smell jar
CODE_SMELL_JAR = os.path.abspath(os.path.join(BASE_DIR, 'metrics/code-quality/code-smells.jar'))

# ck metrics jar
CK_METRICS_JAR = os.path.abspath(os.path.join(BASE_DIR, 'metrics/code-quality/code-quality.jar'))

# readability path
READABILITY_PATH = os.path.abspath(os.path.join(BASE_DIR, 'metrics/readability'))

# the path that contains the projects
PROJECTS = os.path.abspath(os.path.join(BASE_DIR, 'projects'))

# the path that contains the mutation results
MUTATION_RESULTS = os.path.abspath(os.path.join(BASE_DIR, 'mutation_results'))

# the path of the Python package for the mutation
MUTATION_PACKAGE = os.path.abspath(os.path.join(BASE_DIR, 'effectiveness/mutation'))

RESULTS_DIR = os.path.abspath(os.path.join(BASE_DIR, 'results'))

DEFAULT_OPERATORS = ['CONDITIONALS_BOUNDARY',
                     'NEGATE_CONDITIONALS',
                     'MATH',
                     'INCREMENTS',
                     'INVERT_NEGS',
                     'RETURN_VALS',
                     'VOID_METHOD_CALLS']
ADDITIONAL_OPERATORS = ['CONSTRUCTOR_CALLS',
                        'INLINE_CONSTS',
                        'NON_VOID_METHOD_CALLS',
                        'REMOVE_CONDITIONALS',
                        'EXPERIMENTAL_MEMBER_VARIABLE',
                        'EXPERIMENTAL_SWITCH']

ALL_OPERATORS = DEFAULT_OPERATORS + ADDITIONAL_OPERATORS
